base_url: "https://pascallando.github.io"
title: "VictorPy"
theme: cosmo
email: pascal.lando@u-picardie.fr

routes:
    'survey.html': "/survey"

build_dir_name: pascallando.github.io

hooks:
    'after_build':
        - 'deploy_github'

